<?php
/**
 * Yoast SEO integration for AI-generated posts.
 *
 * @package BlogPrivilegeAI
 */

defined( 'ABSPATH' ) || exit;

final class BPAI_SEO_Optimizer {
	private const LOCK_META = '_bpai_updating_seo';
	private const MIN_WORDS = 300;
	private const GREEN_SCORE = 75;

	/** @var self|null */
	private static $instance;

	/**
	 * Return the shared instance.
	 *
	 * @return self
	 */
	public static function instance() {
		if ( null === self::$instance ) {
			self::$instance = new self();
		}

		return self::$instance;
	}

	private function __construct() {
		// This hook runs after meta_input has been persisted. save_post would miss
		// _bpai_generated during the first programmatic insertion.
		add_action( 'wp_after_insert_post', array( $this, 'optimize_post' ), 30, 4 );
		add_filter( 'wp_insert_post_data', array( $this, 'prepare_generated_content' ), 20, 2 );
		add_filter( 'wpseo_metadesc', array( $this, 'filter_metadescription' ) );
	}

	/**
	 * Improve generated content before WordPress saves it.
	 *
	 * The filter is intentionally limited to posts explicitly marked as generated by
	 * the plugin. Existing editorial content is never rewritten.
	 *
	 * @param array $data    Sanitized post data.
	 * @param array $postarr Raw post data.
	 * @return array
	 */
	public function prepare_generated_content( $data, $postarr ) {
		if ( 'post' !== ( $data['post_type'] ?? '' ) || ! $this->is_generated_request( $postarr ) ) {
			return $data;
		}

		$keyword = $this->get_keyword( $data['post_title'] ?? '', $postarr );
		$content = $data['post_content'] ?? '';

		if ( ! $keyword || ! $content ) {
			return $data;
		}

		$data['post_content'] = $this->improve_content( $content, $keyword, $data['post_title'] );
		$data['post_excerpt'] = $this->description( $content, $keyword );

		return $data;
	}

	/**
	 * Populate the fields read by Yoast after a generated article is saved.
	 *
	 * @param int     $post_id Post ID.
	 * @param WP_Post $post    Post object.
	 * @param bool    $update  Whether this is an update.
	 * @param WP_Post $post_before Post object before the update, or null.
	 * @return void
	 */
	public function optimize_post( $post_id, $post, $update, $post_before ) { // phpcs:ignore Generic.CodeAnalysis.UnusedFunctionParameter.FoundAfterLastUsed
		if ( 'post' !== $post->post_type ) {
			return;
		}

		if ( wp_is_post_revision( $post_id ) || wp_is_post_autosave( $post_id ) || get_post_meta( $post_id, self::LOCK_META, true ) ) {
			return;
		}

		if ( ! $this->is_generated_post( $post_id ) ) {
			return;
		}

		$keyword = $this->get_keyword( $post->post_title, array( 'ID' => $post_id ) );
		if ( ! $keyword ) {
			return;
		}

		update_post_meta( $post_id, self::LOCK_META, '1' );
		update_post_meta( $post_id, '_yoast_wpseo_focuskw', $keyword );
		update_post_meta( $post_id, '_yoast_wpseo_metadesc', $this->description( $post->post_content, $keyword ) );
		update_post_meta( $post_id, '_yoast_wpseo_title', $this->seo_title( $post->post_title, $keyword ) );

		$slug = sanitize_title( $keyword );
		if ( ! $update && $slug && false === strpos( (string) $post->post_name, $slug ) ) {
			wp_update_post(
				array(
					'ID'        => $post_id,
					'post_name' => $slug,
				)
			);
		}

		$score = $this->calculate_score( $post, $keyword );
		update_post_meta( $post_id, '_bpai_seo_score', $score );
		if ( self::GREEN_SCORE <= $score ) {
			// API-created posts do not visit Yoast's JavaScript editor. Persist the
			// linkdex only after measurable on-page requirements have passed.
			update_post_meta( $post_id, '_yoast_wpseo_linkdex', $score );
		} else {
			delete_post_meta( $post_id, '_yoast_wpseo_linkdex' );
		}

		delete_post_meta( $post_id, self::LOCK_META );

		/**
		 * Fires after Yoast fields are prepared for a generated article.
		 *
		 * @param int    $post_id Post ID.
		 * @param string $keyword Focus keyphrase.
		 */
		do_action( 'bpai_after_seo_optimization', $post_id, $keyword );
	}

	/**
	 * Use the generated description when Yoast has no manual description.
	 *
	 * @param string $description Current Yoast description.
	 * @return string
	 */
	public function filter_metadescription( $description ) {
		if ( $description || ! is_singular( 'post' ) ) {
			return $description;
		}

		$post_id = get_queried_object_id();
		if ( ! $this->is_generated_post( $post_id ) ) {
			return $description;
		}

		return (string) get_post_meta( $post_id, '_yoast_wpseo_metadesc', true );
	}

	/**
	 * Add useful on-page signals without keyword stuffing.
	 *
	 * @param string $content Content HTML.
	 * @param string $keyword Keyphrase.
	 * @param string $title   Post title.
	 * @return string
	 */
	private function improve_content( $content, $keyword, $title ) {
		$plain = wp_strip_all_tags( $content );
		if ( false === mb_stripos( mb_substr( $plain, 0, 250 ), $keyword ) ) {
			$content = '<p>' . esc_html( $keyword ) . ' é o tema central deste guia prático. Entenda os pontos mais importantes e como aplicá-los para obter melhores resultados.</p>\n' . $content;
		}

		if ( ! preg_match( '/<h2\b/i', $content ) ) {
			$content .= sprintf( "\n<h2>%s: o que você precisa saber</h2>\n", esc_html( $keyword ) );
		}

		if ( ! preg_match( '/<h2[^>]*>[^<]*' . preg_quote( $keyword, '/' ) . '/iu', $content ) ) {
			$content .= sprintf( "\n<h2>Como melhorar resultados com %s</h2>\n", esc_html( $keyword ) );
		}

		if ( ! preg_match( '/<a\s[^>]*href=/i', $content ) ) {
			$content .= sprintf(
				'\n<p>Conheça também outros <a href="%s">conteúdos e soluções da Agência Privilege</a>.</p>',
				esc_url( home_url( '/' ) )
			);
		}

		// Supply a useful accessibility/SEO baseline only when alt is absent.
		$content = preg_replace_callback(
			'/<img\b([^>]*)>/iu',
			static function ( $matches ) use ( $keyword ) {
				$attributes = preg_replace( '/\s*\/\s*$/u', '', $matches[1] );
				if ( preg_match( '/\balt\s*=\s*(["\'])\s*[^\s"\'][^"\']*\1/iu', $attributes ) ) {
					return $matches[0];
				}

				$attributes = preg_replace( '/\s+alt\s*=\s*(["\'])\s*\1/iu', '', $attributes );
				return '<img' . rtrim( $attributes ) . ' alt="' . esc_attr( $keyword ) . '">';
			},
			$content
		);

		if ( ! preg_match( '/<h2[^>]*>\s*(Conclusão|Considerações finais)/iu', $content ) ) {
			$content .= sprintf(
				"\n<h2>Conclusão</h2>\n<p>%s pode gerar resultados consistentes quando existe planejamento, acompanhamento e melhoria contínua. Use as orientações deste artigo como ponto de partida.</p>",
				esc_html( $keyword )
			);
		}

		if ( $this->word_count( wp_strip_all_tags( $content ) ) < self::MIN_WORDS ) {
			$content .= sprintf(
				"\n<h2>Próximos passos</h2>\n<p>Antes de aplicar %1\$s, defina objetivos claros, indicadores e prazos. Analise o cenário atual, priorize as ações de maior impacto e registre os resultados. Esse processo torna a estratégia sobre %2\$s mais segura, mensurável e adequada à realidade do negócio.</p>",
				esc_html( $keyword ),
				esc_html( $title )
			);
		}

		return $content;
	}

	/**
	 * Score objective signals without depending on Yoast's browser editor.
	 *
	 * @param WP_Post $post    Generated post.
	 * @param string  $keyword Focus keyphrase.
	 * @return int Score from 0 to 100.
	 */
	private function calculate_score( $post, $keyword ) {
		$content     = (string) $post->post_content;
		$plain       = trim( preg_replace( '/\s+/u', ' ', wp_strip_all_tags( $content ) ) );
		$description = $this->description( $content, $keyword );
		$score       = 0;

		$score += false !== mb_stripos( (string) $post->post_title, $keyword ) ? 15 : 0;
		$score += false !== mb_stripos( mb_substr( $plain, 0, 250 ), $keyword ) ? 15 : 0;
		$score += preg_match( '/<h[23][^>]*>[^<]*' . preg_quote( $keyword, '/' ) . '/iu', $content ) ? 15 : 0;
		$score += false !== mb_stripos( $description, $keyword ) && mb_strlen( $description ) >= 120 ? 15 : 0;
		$score += $this->word_count( $plain ) >= self::MIN_WORDS ? 15 : 0;
		$score += preg_match( '/<a\s[^>]*href=["\'][^"\']+["\']/iu', $content ) ? 10 : 0;
		$score += preg_match( '/<img\b[^>]*\balt=["\'][^"\']+["\']/iu', $content ) ? 5 : 0;

		$word_count  = $this->word_count( $plain );
		$occurrences = substr_count( mb_strtolower( $plain ), mb_strtolower( $keyword ) );
		$max_uses    = max( 3, (int) ceil( $word_count / 100 ) * 3 );
		$score       += $occurrences >= 2 && $occurrences <= $max_uses ? 10 : 0;

		return min( 100, $score );
	}

	/**
	 * Count Unicode words, including Portuguese accented characters.
	 *
	 * @param string $text Plain text.
	 * @return int
	 */
	private function word_count( $text ) {
		return preg_match_all( '/[\p{L}\p{N}]+(?:[\'\x{2019}-][\p{L}\p{N}]+)*/u', $text, $matches );
	}

	/**
	 * Create a human-readable focus keyphrase.
	 *
	 * @param string $title   Post title.
	 * @param array  $postarr Insert request.
	 * @return string
	 */
	private function get_keyword( $title, $postarr ) {
		$post_id = absint( $postarr['ID'] ?? 0 );
		$keyword = $post_id ? get_post_meta( $post_id, '_bpai_focus_keyphrase', true ) : '';

		if ( ! $keyword && ! empty( $postarr['meta_input']['_bpai_focus_keyphrase'] ) ) {
			$keyword = $postarr['meta_input']['_bpai_focus_keyphrase'];
		}

		if ( ! $keyword ) {
			$parts   = preg_split( '/\s*[:|\-]\s*/u', wp_strip_all_tags( $title ), 2 );
			$keyword = $parts[0] ?? $title;
		}

		$words = preg_split( '/\s+/u', trim( $keyword ) );
		return sanitize_text_field( implode( ' ', array_slice( $words, 0, 8 ) ) );
	}

	/**
	 * Create a description in Yoast's recommended range.
	 *
	 * @param string $content Content HTML.
	 * @param string $keyword Keyphrase.
	 * @return string
	 */
	private function description( $content, $keyword ) {
		$text = trim( preg_replace( '/\s+/u', ' ', wp_strip_all_tags( strip_shortcodes( $content ) ) ) );
		if ( false === mb_stripos( mb_substr( $text, 0, 155 ), $keyword ) ) {
			$text = $keyword . ': ' . lcfirst( $text );
		}

		return sanitize_text_field( wp_html_excerpt( $text, 155, '…' ) );
	}

	/**
	 * Keep the SEO title concise and start it with the keyphrase.
	 *
	 * @param string $title   Original title.
	 * @param string $keyword Keyphrase.
	 * @return string
	 */
	private function seo_title( $title, $keyword ) {
		$title = false === mb_stripos( $title, $keyword ) ? $keyword . ' - ' . $title : $title;
		return sanitize_text_field( wp_html_excerpt( $title, 58, '' ) . ' %%sep%% %%sitename%%' );
	}

	/**
	 * Identify explicit requests from the article generator.
	 *
	 * @param array $postarr Post request.
	 * @return bool
	 */
	private function is_generated_request( $postarr ) {
		if ( ! empty( $postarr['meta_input']['_bpai_generated'] ) ) {
			return true;
		}

		return (bool) apply_filters( 'bpai_is_generated_request', false, $postarr );
	}

	/**
	 * Determine whether a post belongs to the generator.
	 *
	 * @param int $post_id Post ID.
	 * @return bool
	 */
	private function is_generated_post( $post_id ) {
		$is_generated = (bool) get_post_meta( $post_id, '_bpai_generated', true );
		return (bool) apply_filters( 'bpai_is_generated_post', $is_generated, $post_id );
	}
}
