<?php
declare(strict_types=1);

namespace JuntaPlay\Setup;

use JuntaPlay\Data\Pools;
use JuntaPlay\Data\Quotas;

use function current_time;
use function get_option;
use function update_option;

defined('ABSPATH') || exit;

class PoolSeeder
{
    private const OPTION_KEY = 'juntaplay_pools_seeded_v1';

    /**
     * Populate the preapproved pools from the annex reference.
     *
     * @return array<string, mixed>
     */
    public function seed(): array
    {
        $pools = $this->get_pools();
        $created = 0;

        foreach ($pools as $pool) {
            $pool_id = Pools::create_or_update($pool);

            if (!$pool_id) {
                continue;
            }

            Pools::ensure_product($pool_id);
            Quotas::seed($pool_id);
            $created++;
        }

        update_option(self::OPTION_KEY, [
            'seeded_at' => current_time('mysql'),
            'total'     => $created,
        ]);

        return [
            'total'   => count($pools),
            'created' => $created,
        ];
    }

    /**
     * Seed once automatically if no pools exist and the option is not set.
     */
    public function maybe_seed_defaults(): void
    {
        if (get_option(self::OPTION_KEY)) {
            return;
        }

        $existing = Pools::query([
            'per_page' => 1,
        ]);

        if (!empty($existing['total'])) {
            return;
        }

        $this->seed();
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    private function get_pools(): array
    {
        return [
            [
                'title'        => 'YouTube Premium',
                'slug'         => 'youtube-premium',
                'price'        => 34.90,
                'quota_start'  => 1,
                'quota_end'    => 6,
                'category'     => 'video',
                'excerpt'      => 'Filmes e músicas sem anúncios com downloads para até 6 perfis.',
                'is_featured'  => true,
                'status'       => 'publish',
            ],
            [
                'title'        => 'Spotify',
                'slug'         => 'spotify',
                'price'        => 24.90,
                'quota_start'  => 1,
                'quota_end'    => 6,
                'category'     => 'music',
                'excerpt'      => 'Streaming de música premium para toda a família sem anúncios.',
                'is_featured'  => true,
                'status'       => 'publish',
            ],
            [
                'title'        => 'Mubi',
                'slug'         => 'mubi',
                'price'        => 27.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'video',
                'excerpt'      => 'Cinemateca com curadoria diária de filmes e clássicos.',
                'is_featured'  => true,
                'status'       => 'publish',
            ],
            [
                'title'        => 'Canva',
                'slug'         => 'canva',
                'price'        => 29.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'office',
                'excerpt'      => 'Ferramentas de design e apresentações colaborativas.',
                'is_featured'  => true,
                'status'       => 'publish',
            ],
            [
                'title'        => 'CapCut',
                'slug'         => 'capcut',
                'price'        => 19.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'software',
                'excerpt'      => 'Edição de vídeo profissional com recursos premium.',
                'is_featured'  => true,
                'status'       => 'publish',
            ],
            [
                'title'        => 'Duolingo',
                'slug'         => 'duolingo',
                'price'        => 29.90,
                'quota_start'  => 1,
                'quota_end'    => 6,
                'category'     => 'education',
                'excerpt'      => 'Aulas de idiomas gamificadas para até 6 alunos.',
                'is_featured'  => true,
                'status'       => 'publish',
            ],
            [
                'title'        => 'Crunchyroll',
                'slug'         => 'crunchyroll',
                'price'        => 24.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'video',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Letterboxd',
                'slug'         => 'letterboxd',
                'price'        => 14.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'video',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Kindle Unlimited',
                'slug'         => 'kindle-unlimited',
                'price'        => 27.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'reading',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Google Drive',
                'slug'         => 'google-drive',
                'price'        => 12.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'office',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Microsoft 365',
                'slug'         => 'microsoft-365',
                'price'        => 36.90,
                'quota_start'  => 1,
                'quota_end'    => 6,
                'category'     => 'office',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Notion',
                'slug'         => 'notion',
                'price'        => 21.90,
                'quota_start'  => 1,
                'quota_end'    => 6,
                'category'     => 'office',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Evernote',
                'slug'         => 'evernote',
                'price'        => 18.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'office',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'MEGA',
                'slug'         => 'mega',
                'price'        => 19.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'software',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Dropbox',
                'slug'         => 'dropbox',
                'price'        => 29.90,
                'quota_start'  => 1,
                'quota_end'    => 6,
                'category'     => 'office',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Netflix',
                'slug'         => 'netflix',
                'price'        => 44.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'video',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Disney Plus',
                'slug'         => 'disney-plus',
                'price'        => 34.90,
                'quota_start'  => 1,
                'quota_end'    => 6,
                'category'     => 'video',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'HBO Max',
                'slug'         => 'hbo-max',
                'price'        => 29.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'video',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Star Plus',
                'slug'         => 'star-plus',
                'price'        => 28.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'video',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Prime Video',
                'slug'         => 'prime-video',
                'price'        => 19.90,
                'quota_start'  => 1,
                'quota_end'    => 6,
                'category'     => 'video',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Paramount Plus',
                'slug'         => 'paramount-plus',
                'price'        => 19.90,
                'quota_start'  => 1,
                'quota_end'    => 6,
                'category'     => 'video',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Apple TV Plus',
                'slug'         => 'apple-tv-plus',
                'price'        => 19.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'video',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Globoplay',
                'slug'         => 'globoplay',
                'price'        => 28.90,
                'quota_start'  => 1,
                'quota_end'    => 6,
                'category'     => 'video',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'PlayPlus',
                'slug'         => 'playplus',
                'price'        => 21.90,
                'quota_start'  => 1,
                'quota_end'    => 4,
                'category'     => 'video',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Telecine',
                'slug'         => 'telecine',
                'price'        => 29.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'video',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Apple Music',
                'slug'         => 'apple-music',
                'price'        => 21.90,
                'quota_start'  => 1,
                'quota_end'    => 6,
                'category'     => 'music',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Deezer',
                'slug'         => 'deezer',
                'price'        => 21.90,
                'quota_start'  => 1,
                'quota_end'    => 6,
                'category'     => 'music',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Tidal',
                'slug'         => 'tidal',
                'price'        => 29.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'music',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'YouTube Music',
                'slug'         => 'youtube-music',
                'price'        => 21.90,
                'quota_start'  => 1,
                'quota_end'    => 6,
                'category'     => 'music',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Apple Arcade',
                'slug'         => 'apple-arcade',
                'price'        => 19.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'games',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Nintendo Switch Online',
                'slug'         => 'nintendo-switch-online',
                'price'        => 24.90,
                'quota_start'  => 1,
                'quota_end'    => 8,
                'category'     => 'games',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Xbox Game Pass Ultimate',
                'slug'         => 'xbox-game-pass-ultimate',
                'price'        => 44.90,
                'quota_start'  => 1,
                'quota_end'    => 6,
                'category'     => 'games',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'PlayStation Plus',
                'slug'         => 'playstation-plus',
                'price'        => 44.90,
                'quota_start'  => 1,
                'quota_end'    => 6,
                'category'     => 'games',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'EA Play',
                'slug'         => 'ea-play',
                'price'        => 24.90,
                'quota_start'  => 1,
                'quota_end'    => 6,
                'category'     => 'games',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Steam',
                'slug'         => 'steam',
                'price'        => 0.00,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'games',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Epic Games Store',
                'slug'         => 'epic-games-store',
                'price'        => 0.00,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'games',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Udemy',
                'slug'         => 'udemy',
                'price'        => 27.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'education',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Coursera',
                'slug'         => 'coursera',
                'price'        => 32.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'education',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Alura',
                'slug'         => 'alura',
                'price'        => 59.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'education',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Skillshare',
                'slug'         => 'skillshare',
                'price'        => 34.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'education',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Google One',
                'slug'         => 'google-one',
                'price'        => 12.90,
                'quota_start'  => 1,
                'quota_end'    => 6,
                'category'     => 'office',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'iCloud Plus',
                'slug'         => 'icloud-plus',
                'price'        => 12.90,
                'quota_start'  => 1,
                'quota_end'    => 6,
                'category'     => 'office',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Adobe Creative Cloud',
                'slug'         => 'adobe-creative-cloud',
                'price'        => 79.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'software',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Adobe Lightroom',
                'slug'         => 'adobe-lightroom',
                'price'        => 29.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'software',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Adobe Photoshop',
                'slug'         => 'adobe-photoshop',
                'price'        => 39.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'software',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Figma',
                'slug'         => 'figma',
                'price'        => 29.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'software',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Trello',
                'slug'         => 'trello',
                'price'        => 21.90,
                'quota_start'  => 1,
                'quota_end'    => 6,
                'category'     => 'office',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Slack',
                'slug'         => 'slack',
                'price'        => 29.90,
                'quota_start'  => 1,
                'quota_end'    => 8,
                'category'     => 'office',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Discord Nitro',
                'slug'         => 'discord-nitro',
                'price'        => 19.90,
                'quota_start'  => 1,
                'quota_end'    => 6,
                'category'     => 'other',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Zoom Pro',
                'slug'         => 'zoom-pro',
                'price'        => 34.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'office',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Calendly',
                'slug'         => 'calendly',
                'price'        => 19.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'office',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'NordVPN',
                'slug'         => 'nordvpn',
                'price'        => 18.90,
                'quota_start'  => 1,
                'quota_end'    => 6,
                'category'     => 'security',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'ExpressVPN',
                'slug'         => 'expressvpn',
                'price'        => 24.90,
                'quota_start'  => 1,
                'quota_end'    => 6,
                'category'     => 'security',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Surfshark VPN',
                'slug'         => 'surfshark-vpn',
                'price'        => 16.90,
                'quota_start'  => 1,
                'quota_end'    => 6,
                'category'     => 'security',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Avast SecureLine',
                'slug'         => 'avast-secureline',
                'price'        => 19.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'security',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Dashlane',
                'slug'         => 'dashlane',
                'price'        => 19.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'security',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'LastPass',
                'slug'         => 'lastpass',
                'price'        => 14.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'security',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Grammarly',
                'slug'         => 'grammarly',
                'price'        => 24.90,
                'quota_start'  => 1,
                'quota_end'    => 6,
                'category'     => 'ai',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Headspace',
                'slug'         => 'headspace',
                'price'        => 19.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'lifestyle',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Calm',
                'slug'         => 'calm',
                'price'        => 19.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'lifestyle',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Strava',
                'slug'         => 'strava',
                'price'        => 19.90,
                'quota_start'  => 1,
                'quota_end'    => 6,
                'category'     => 'lifestyle',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Fitbit Premium',
                'slug'         => 'fitbit-premium',
                'price'        => 19.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'lifestyle',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Tinder Gold',
                'slug'         => 'tinder-gold',
                'price'        => 29.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'lifestyle',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Bumble Boost',
                'slug'         => 'bumble-boost',
                'price'        => 29.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'lifestyle',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'LinkedIn Premium',
                'slug'         => 'linkedin-premium',
                'price'        => 59.90,
                'quota_start'  => 1,
                'quota_end'    => 6,
                'category'     => 'office',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Medium Membership',
                'slug'         => 'medium-membership',
                'price'        => 24.90,
                'quota_start'  => 1,
                'quota_end'    => 5,
                'category'     => 'reading',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
            [
                'title'        => 'Google Workspace',
                'slug'         => 'google-workspace',
                'price'        => 32.90,
                'quota_start'  => 1,
                'quota_end'    => 6,
                'category'     => 'office',
                'excerpt'      => '',
                'status'       => 'publish',
            ],
        ];
    }
}
